"""
Part 2 (local): turn a Kaggle results folder into report tables and figures.

    python analysis/make_report.py                                  # default run, ResNet-50 as mCE baseline
    python analysis/make_report.py results/<run_name> --baseline resnet50

Input : results/<run_name>/  (raw output of kaggle/robust_training.ipynb)
Output: reports/tables/*.csv|.md|.tex   reports/figures/*.png
        + the results table between the RESULTS markers in README.md

Metrics (all on the test set, accuracy in %):
  Clean accuracy, macro precision / recall / F1, cross-entropy loss
  Accuracy vs Severity      acc(d, s) for every degradation d and level s     (Hendrycks & Dietterich, 2019)
  mCA                       mean corrupted accuracy over all 15 conditions
  Retention rate            RR(d, s) = acc(d, s) / acc_clean
  Confidence drop           mean max-softmax (clean) - mean max-softmax (degraded)
  Corruption Error          CE(d) = sum_s err_model(d, s) / sum_s err_baseline(d, s)  (x100; baseline = 100)
  mCE                       mean of CE(d) over degradations
  Critical Severity Point   first level where RR < threshold (from the Kaggle run, default 0.90)
"""
import argparse
import os
import re
import shutil
import sys

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from kaggle_results import load_run  # noqa: E402

DEFAULT_RUN = os.path.join(ROOT, 'results', 'run_fix_data_leak')
TABLES = os.path.join(ROOT, 'reports', 'tables')
FIGURES = os.path.join(ROOT, 'reports', 'figures')

MODEL_LABEL = {'resnet50': 'ResNet-50', 'convnext_tiny': 'ConvNeXt-T', 'deit_small': 'DeiT-S',
               'swin_tiny': 'Swin-T', 'vgg16': 'VGG-16'}
MODEL_COLOR = {'resnet50': '#2a78d6', 'convnext_tiny': '#eb6834', 'deit_small': '#1baf7a',
               'swin_tiny': '#eda100', 'vgg16': '#e87ba4'}
DEG_LABEL = {'gaussian_blur': 'Gaussian blur', 'gaussian_noise': 'Gaussian noise', 'low_light': 'Low light',
             'jpeg': 'JPEG compression', 'pixelate': 'Resolution downscaling'}
SEQ = LinearSegmentedColormap.from_list('seq', ['#fcfcfb', '#9ec5f4', '#2a78d6', '#104281'])
INK, MUTED = '#0b0b0b', '#898781'

plt.rcParams.update({'font.size': 9, 'axes.edgecolor': MUTED, 'axes.labelcolor': INK, 'xtick.color': INK,
                     'ytick.color': INK, 'axes.spines.top': False, 'axes.spines.right': False,
                     'figure.dpi': 150, 'savefig.bbox': 'tight'})


# --------------------------------------------------------------------------- table writers
def _tex_escape(s):
    return str(s).replace('_', r'\_').replace('%', r'\%').replace('&', r'\&')


def save_table(df, name, fmt='{:.2f}', best=None, note=None):
    """Write <name>.csv (full precision), .md (rounded) and .tex (booktabs tabular, best value in bold).
    best = {column: 'max' | 'min'} marks the best entry of each listed column."""
    df.to_csv(os.path.join(TABLES, f'{name}.csv'), index=False)

    def cell(v, col):
        f = fmt.get(col, '{:.2f}') if isinstance(fmt, dict) else fmt
        if isinstance(v, (float, np.floating)):
            return '' if np.isnan(v) else f.format(v)
        return str(v)

    shown = df.copy()
    bold = {}
    for col, how in (best or {}).items():
        vals = pd.to_numeric(df[col], errors='coerce')
        if vals.notna().any():
            target = vals.max() if how == 'max' else vals.min()
            bold[col] = set(df.index[np.isclose(vals, target)])
    md_rows = ['| ' + ' | '.join(map(str, df.columns)) + ' |',
               '|' + '|'.join(['---'] * len(df.columns)) + '|']
    tex_rows = []
    for i, r in shown.iterrows():
        md_cells, tex_cells = [], []
        for c in df.columns:
            s = cell(r[c], c)
            is_bold = i in bold.get(c, set())
            md_cells.append(f'**{s}**' if is_bold and s else s)
            tex_cells.append(rf'\textbf{{{_tex_escape(s)}}}' if is_bold and s else _tex_escape(s))
        md_rows.append('| ' + ' | '.join(md_cells) + ' |')
        tex_rows.append(' & '.join(tex_cells) + r' \\')
    md = '\n'.join(md_rows) + ('\n\n' + note if note else '') + '\n'
    with open(os.path.join(TABLES, f'{name}.md'), 'w', encoding='utf-8') as f:
        f.write(md)
    align = 'l' + 'r' * (len(df.columns) - 1)
    tex = (f'% generated by analysis/make_report.py -- do not edit by hand\n'
           f'\\begin{{tabular}}{{{align}}}\n\\toprule\n'
           + ' & '.join(_tex_escape(c) for c in df.columns) + r' \\' + '\n\\midrule\n'
           + '\n'.join(tex_rows) + '\n\\bottomrule\n\\end{tabular}\n')
    with open(os.path.join(TABLES, f'{name}.tex'), 'w', encoding='utf-8') as f:
        f.write(tex)
    return md


# --------------------------------------------------------------------------- tables
def build_tables(run, baseline):
    bs = run.by_severity
    models = run.models
    degs = [d for d in DEG_LABEL if d in set(bs.degradation)]
    lab = lambda m: MODEL_LABEL.get(m, m)
    out = {}

    # Corruption Error (Hendrycks & Dietterich 2019), baseline = one of our models (=100)
    err = bs[bs.degradation != 'clean'].assign(error=lambda t: 100 - t.accuracy)
    sum_err = err.groupby(['model', 'degradation']).error.sum()
    ce = pd.DataFrame({m: {d: 100 * sum_err[(m, d)] / sum_err[(baseline, d)] for d in degs} for m in models}).T
    mce = ce.mean(axis=1)

    # 1. main results
    rows = []
    for m in models:
        met = run.metrics(m)
        c, o = met['clean'], met['overall']
        rows.append({'Model': lab(m), 'Clean acc': c['accuracy'], 'Precision': c['precision_macro'],
                     'Recall': c['recall_macro'], 'F1': c['f1_macro'], 'CE loss': c['ce_loss'],
                     'mCA': o['mean_corrupted_accuracy'], 'Retention': 100 * o['mean_retention_rate'],
                     'Conf. drop': 100 * o['mean_confidence_drop'], 'mCE': mce[m]})
    main = pd.DataFrame(rows)
    out['main_results'] = save_table(
        main, 'main_results', fmt={'CE loss': '{:.3f}', 'mCE': '{:.1f}'},
        best={'Clean acc': 'max', 'Precision': 'max', 'Recall': 'max', 'F1': 'max', 'CE loss': 'min',
              'mCA': 'max', 'Retention': 'max', 'Conf. drop': 'min', 'mCE': 'min'},
        note=(f'Test set: {len(run.labels)} images. Clean acc / precision / recall / F1 / mCA / retention in %, '
              f'CE loss = cross-entropy on clean images, conf. drop in percentage points of mean max-softmax, '
              f'mCE relative to {lab(baseline)} (= 100, lower is better).'))

    # 2. accuracy vs severity (long table: one row per degradation x model)
    rows = []
    for d in degs:
        for m in models:
            sub = bs[(bs.model == m) & (bs.degradation == d)].sort_values('severity')
            clean = bs[(bs.model == m) & (bs.degradation == 'clean')].accuracy.item()
            codes = list(sub.code)
            rows.append({'Degradation': f"{DEG_LABEL[d]} ({codes[0]}-{codes[-1]})", 'Model': lab(m),
                         'Clean': clean, 'Level 1': sub.accuracy.iloc[0], 'Level 2': sub.accuracy.iloc[1],
                         'Level 3': sub.accuracy.iloc[2], 'Mean': sub.accuracy.mean()})
    avs = pd.DataFrame(rows)
    out['accuracy_vs_severity'] = save_table(avs, 'accuracy_vs_severity')

    # 3. mean accuracy per degradation (models x degradations) -- compact view of table 2
    pivot = avs.pivot(index='Model', columns='Degradation', values='Mean').reindex([lab(m) for m in models])
    pivot.columns = [c.split(' (')[0] for c in pivot.columns]
    pivot = pivot[[DEG_LABEL[d] for d in degs]].reset_index()
    out['accuracy_per_degradation'] = save_table(pivot, 'accuracy_per_degradation',
                                                 best={c: 'max' for c in pivot.columns[1:]})

    # 4. corruption error per degradation + mCE
    ce_t = ce.rename(index=lab, columns=DEG_LABEL)
    ce_t['mCE'] = mce.rename(index=lab)
    ce_t = ce_t.reset_index().rename(columns={'index': 'Model'})
    out['corruption_error'] = save_table(ce_t, 'corruption_error', fmt='{:.1f}',
                                         best={c: 'min' for c in ce_t.columns[1:]},
                                         note=f'Corruption Error relative to {lab(baseline)} (= 100). Lower is better.')

    # 5. retention per degradation + critical severity point
    rows = []
    for m in models:
        corr = run.metrics(m)['corruption']
        r = {'Model': lab(m)}
        for d in degs:
            csp = corr[d]['critical_severity_point']
            r[DEG_LABEL[d]] = f"{100 * corr[d]['mean_retention_rate']:.1f} ({csp if csp else '-'})"
        rows.append(r)
    th = run.info.get('critical_retention', 0.9)
    out['retention_csp'] = save_table(pd.DataFrame(rows), 'retention_csp',
                                      note=f'Mean retention rate in % (critical severity point: first level where '
                                           f'retention < {th:.2f}; "-" = never).')

    # 6. per-class F1 on clean images
    rows = []
    for k, cname in enumerate(run.classes):
        r = {'Class': cname.replace('_', ' ')}
        for m in models:
            r[lab(m)] = run.metrics(m)['clean']['per_class'][cname]['f1']
        rows.append(r)
    out['per_class_f1'] = save_table(pd.DataFrame(rows), 'per_class_f1')
    return out, main, avs, ce


# --------------------------------------------------------------------------- figures
def fig_accuracy_vs_severity(run, path):
    bs = run.by_severity
    degs = [d for d in DEG_LABEL if d in set(bs.degradation)]
    fig, axes = plt.subplots(1, len(degs), figsize=(2.6 * len(degs), 2.8), sharey=True)
    for ax, d in zip(np.atleast_1d(axes), degs):
        for m in run.models:
            sub = bs[(bs.model == m) & (bs.degradation == d)].sort_values('severity')
            clean = bs[(bs.model == m) & (bs.degradation == 'clean')].accuracy.item()
            ax.plot([0] + list(sub.severity), [clean] + list(sub.accuracy), color=MODEL_COLOR.get(m),
                    lw=2, marker='o', ms=4, label=MODEL_LABEL.get(m, m))
        codes = list(bs[(bs.degradation == d)].sort_values('severity').drop_duplicates('severity').code)
        ax.set_xticks(range(len(codes) + 1))
        ax.set_xticklabels(['clean'] + codes)
        ax.set_title(DEG_LABEL[d], fontsize=9)
        ax.grid(axis='y', alpha=0.3, lw=0.6)
    np.atleast_1d(axes)[0].set_ylabel('Test accuracy (%)')
    fig.legend(*np.atleast_1d(axes)[0].get_legend_handles_labels(), loc='lower center',
               ncol=len(run.models), frameon=False, bbox_to_anchor=(0.5, -0.06))
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def _draw_cm(ax, cm, classes, title):
    norm = cm / np.maximum(cm.sum(1, keepdims=True), 1)
    ax.imshow(norm, cmap=SEQ, vmin=0, vmax=1)
    k = len(classes)
    ax.set_xticks(range(k)); ax.set_yticks(range(k))
    ax.set_xticklabels(classes, rotation=45, ha='right', fontsize=6)
    ax.set_yticklabels(classes, fontsize=6)
    for i in range(k):
        for j in range(k):
            if cm[i, j]:
                ax.text(j, i, cm[i, j], ha='center', va='center', fontsize=5,
                        color='#ffffff' if norm[i, j] > 0.55 else INK)
    ax.set_title(title, fontsize=8)
    for s in ax.spines.values():
        s.set_visible(False)


def fig_confusions(run, path, which='clean'):
    """which='clean' -> clean confusion matrix per model; 'hardest' -> each model's lowest-accuracy condition."""
    classes = [c.replace('_', ' ') for c in run.classes]
    n = len(run.models)
    cols = 2 if n > 1 else 1
    rows = int(np.ceil(n / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(4.2 * cols, 4.0 * rows), squeeze=False)
    bs = run.by_severity
    for ax, m in zip(axes.flat, run.models):
        if which == 'clean':
            code, acc = 'clean', bs[(bs.model == m) & (bs.code == 'clean')].accuracy.item()
        else:
            row = bs[(bs.model == m) & (bs.code != 'clean')].sort_values('accuracy').iloc[0]
            code, acc = row.code, row.accuracy
        _draw_cm(ax, run.cm(m, code), classes, f'{MODEL_LABEL.get(m, m)} - {code} (acc {acc:.1f}%)')
    for ax in list(axes.flat)[n:]:
        ax.axis('off')
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def fig_retention_heatmap(run, path):
    bs = run.by_severity[run.by_severity.code != 'clean']
    codes = [c for c in run.codes if c != 'clean']
    mat = np.array([[bs[(bs.model == m) & (bs.code == c)].retention_rate.item() * 100 for c in codes]
                    for m in run.models])
    fig, ax = plt.subplots(figsize=(0.55 * len(codes) + 1.6, 0.45 * len(run.models) + 1.0))
    im = ax.imshow(mat, cmap=SEQ, vmin=max(0, mat.min() - 5), vmax=100, aspect='auto')
    ax.set_xticks(range(len(codes))); ax.set_xticklabels(codes)
    ax.set_yticks(range(len(run.models))); ax.set_yticklabels([MODEL_LABEL.get(m, m) for m in run.models])
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            ax.text(j, i, f'{mat[i, j]:.0f}', ha='center', va='center', fontsize=7,
                    color='#ffffff' if (mat[i, j] - im.norm.vmin) / (100 - im.norm.vmin) > 0.6 else INK)
    for s in ax.spines.values():
        s.set_visible(False)
    cb = fig.colorbar(im, ax=ax, fraction=0.03, pad=0.02)
    cb.set_label('Retention rate (%)')
    ax.set_title('Retention rate = degraded accuracy / clean accuracy', fontsize=9)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def fig_training_curves(run, path):
    fig, axes = plt.subplots(1, 2, figsize=(8, 2.8))
    any_hist = False
    for m in run.models:
        h = run.history(m)
        if h is None or h.empty:
            continue
        any_hist = True
        kw = dict(color=MODEL_COLOR.get(m), lw=2, marker='o', ms=3, label=MODEL_LABEL.get(m, m))
        axes[0].plot(h.epoch, h.val_acc, **kw)
        axes[1].plot(h.epoch, h.val_loss, **kw)
    if not any_hist:
        plt.close(fig)
        return False
    axes[0].set_ylabel('Validation accuracy (%)')
    axes[1].set_ylabel('Validation loss')
    for ax in axes:
        ax.set_xlabel('Epoch')
        ax.grid(axis='y', alpha=0.3, lw=0.6)
    axes[1].legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return True


# --------------------------------------------------------------------------- README
def update_readme(main_md, run, baseline):
    readme = os.path.join(ROOT, 'README.md')
    if not os.path.exists(readme):
        return False
    with open(readme, encoding='utf-8') as f:
        text = f.read()
    start, end = '<!-- RESULTS:START -->', '<!-- RESULTS:END -->'
    if start not in text or end not in text:
        return False
    block = (f'{start}\n_Generated by `analysis/make_report.py` from `results/{run.name}` '
             f'(test set: {len(run.labels)} images, mCE baseline: {MODEL_LABEL.get(baseline, baseline)})._\n\n'
             f'{main_md}{end}')
    text = re.sub(re.escape(start) + r'.*?' + re.escape(end), lambda _: block, text, flags=re.S)
    with open(readme, 'w', encoding='utf-8') as f:
        f.write(text)
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('run', nargs='?', default=DEFAULT_RUN, help='results folder (or zip) from Kaggle')
    ap.add_argument('--baseline', default='resnet50', help='model used as mCE baseline (= 100)')
    args = ap.parse_args()

    os.makedirs(TABLES, exist_ok=True)
    os.makedirs(FIGURES, exist_ok=True)
    run = load_run(args.run)
    if args.baseline not in run.models:
        sys.exit(f'--baseline {args.baseline!r} is not in this run: {run.models}')
    print(run)

    out, main_df, _, _ = build_tables(run, args.baseline)
    fig_accuracy_vs_severity(run, os.path.join(FIGURES, 'accuracy_vs_severity.png'))
    fig_confusions(run, os.path.join(FIGURES, 'confusion_clean.png'), 'clean')
    fig_confusions(run, os.path.join(FIGURES, 'confusion_hardest.png'), 'hardest')
    fig_retention_heatmap(run, os.path.join(FIGURES, 'retention_heatmap.png'))
    fig_training_curves(run, os.path.join(FIGURES, 'training_curves.png'))
    preview = os.path.join(run.folder, 'degradation_preview.png')
    if os.path.exists(preview):
        shutil.copy2(preview, os.path.join(FIGURES, 'degradation_examples.png'))

    readme_done = update_readme(out['main_results'], run, args.baseline)
    print('\n' + out['main_results'])
    print(f'Tables  -> {os.path.relpath(TABLES, ROOT)}/  ({", ".join(out)})')
    print(f'Figures -> {os.path.relpath(FIGURES, ROOT)}/  ({", ".join(sorted(os.listdir(FIGURES)))})')
    print('README results table updated' if readme_done else 'README not updated (markers not found)')


if __name__ == '__main__':
    main()
